package Interfaz;

import Datos.recuperacionCorreo;
import Datos.CifradoContraseña;
import Datos.SQL;
import Interfaz.Login;
import Interfaz.Registro;
import java.util.Properties;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class recuperacion extends javax.swing.JFrame {

    SQL sql = new SQL();
    recuperacionCorreo cor = new recuperacionCorreo();

    public recuperacion() {
       
        initComponents();
        codigo4.setEditable(false);
        setLocationRelativeTo(null);
        confirmar.setEnabled(false);
        try {
            setIconImage(new ImageIcon(getClass().getResource("../Imagenes/icono.png")).getImage());
        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lblmail5 = new javax.swing.JLabel();
        codigo4 = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblmail1 = new javax.swing.JLabel();
        panelPass = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pass1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        pass2 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        ocultar = new javax.swing.JLabel();
        mostrar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botonAtras = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        panelConfirm = new javax.swing.JPanel();
        confirmar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("XXXXXX");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 90, 30));

        lblmail5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblmail5.setForeground(new java.awt.Color(102, 102, 102));
        lblmail5.setText("e-mail");
        jPanel5.add(lblmail5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        codigo4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        codigo4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codigo4.setBorder(null);
        codigo4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                codigo4FocusGained(evt);
            }
        });
        codigo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigo4ActionPerformed(evt);
            }
        });
        jPanel5.add(codigo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 250, 50));

        correo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        correo.setForeground(new java.awt.Color(51, 51, 51));
        correo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        correo.setBorder(null);
        correo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                correoMouseClicked(evt);
            }
        });
        jPanel5.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 340, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("___________________");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 210, 20));

        lblmail1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblmail1.setForeground(new java.awt.Color(102, 102, 102));
        lblmail1.setText("e-mail");
        jPanel5.add(lblmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        panelPass.setBackground(new java.awt.Color(255, 255, 255));
        panelPass.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Nueva contraseña");
        panelPass.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("_______________________");
        panelPass.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));

        pass1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        pass1.setBorder(null);
        pass1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pass1FocusGained(evt);
            }
        });
        pass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pass1MouseClicked(evt);
            }
        });
        panelPass.add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -10, 250, 40));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Repetir Nueva Contraseña");
        panelPass.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        pass2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        pass2.setBorder(null);
        pass2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pass2FocusGained(evt);
            }
        });
        panelPass.add(pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 250, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("_______________________");
        panelPass.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 280, 20));

        ocultar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ocultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ojo.png"))); // NOI18N
        ocultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ocultarMouseClicked(evt);
            }
        });
        panelPass.add(ocultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        mostrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ojocerrado.png"))); // NOI18N
        mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarMouseClicked(evt);
            }
        });
        panelPass.add(mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jPanel5.add(panelPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 320, 120));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("_______________________");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, 20));

        botonAtras.setBackground(new java.awt.Color(255, 255, 255));
        botonAtras.setFont(new java.awt.Font("Nirmala UI", 0, 19)); // NOI18N
        botonAtras.setForeground(new java.awt.Color(255, 0, 1));
        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-back-30.png"))); // NOI18N
        botonAtras.setBorder(null);
        botonAtras.setBorderPainted(false);
        botonAtras.setContentAreaFilled(false);
        botonAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonAtras.setDefaultCapable(false);
        botonAtras.setFocusPainted(false);
        botonAtras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAtras.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botonAtras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAtrasMouseExited(evt);
            }
        });
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });
        jPanel5.add(botonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Restablecer contraseña");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 280, 70));

        confirmar.setBackground(new java.awt.Color(17, 17, 17));
        confirmar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        confirmar.setForeground(new java.awt.Color(129, 129, 129));
        confirmar.setText("Confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConfirmLayout = new javax.swing.GroupLayout(panelConfirm);
        panelConfirm.setLayout(panelConfirmLayout);
        panelConfirmLayout.setHorizontalGroup(
            panelConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(confirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        panelConfirmLayout.setVerticalGroup(
            panelConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(confirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel5.add(panelConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 150, 50));

        jButton1.setBackground(new java.awt.Color(17, 17, 17));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(129, 129, 129));
        jButton1.setText("Enviar Codigo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 150, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
        jLabel1.setText("");
    }//GEN-LAST:event_codigoActionPerformed

    private void correoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_correoMouseClicked
        lblmail.setText("");
    }//GEN-LAST:event_correoMouseClicked

    private void botonAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtrasMouseEntered

    }//GEN-LAST:event_botonAtrasMouseEntered

    private void botonAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtrasMouseExited

    }//GEN-LAST:event_botonAtrasMouseExited

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed

        Login lol = new Login();
        this.dispose();
        lol.setVisible(true);
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        recuperacionCorreo cor = new recuperacionCorreo();
        Properties prop = new Properties();
        Session ses = Session.getDefaultInstance(prop);
        MimeMessage mail = new MimeMessage(ses);
        SQL sql = new SQL();
        cor.setCorreo(correo.getText());
        int codigo = sql.recibirCodigo(cor);

        if (codigo != 0) {

            prop.setProperty("mail.smtp.host", "smtp.gmail.com");
            prop.setProperty("mail.smtp.starttls.enable", "true");
            prop.setProperty("mail.smtp.port", "587");
            prop.setProperty("mail.smtp.auth", "true");

            String correoEnvio = "rodripereira2625@gmail.com";
            String contrasena = "26280259rodrigo";
            String enviar = cor.getCorreo();
            String asunto = "Recuperación";
            String mensaje = "Código de recuperación " + codigo;

            try {
                mail.setFrom(new InternetAddress(correoEnvio));
                mail.addRecipient(Message.RecipientType.TO, new InternetAddress(enviar));
                mail.setSubject(asunto);
                mail.setText(mensaje);

                Transport transporte = ses.getTransport("smtp");
                transporte.connect(correoEnvio, contrasena);
                transporte.sendMessage(mail, mail.getRecipients(Message.RecipientType.TO));
                transporte.close();
                JOptionPane.showMessageDialog(null, "Se envió un correo de recuperación a " + cor.getCorreo());

            } catch (AddressException ex) {
                Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
                ex.printStackTrace();
            } catch (MessagingException ex) {
                Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Properties prop = new Properties();
        Session ses = Session.getDefaultInstance(prop);
        MimeMessage mail = new MimeMessage(ses);

        cor.setCorreo(correo.getText());
        if (sql.existeCorreo(cor) == 1) {

            int codigo = sql.recibirCodigo(cor);

            cor.setCodigo(codigo);

            if (cor.getCodigo() != 0) {

                prop.setProperty("mail.smtp.host", "smtp.gmail.com");
                prop.setProperty("mail.smtp.starttls.enable", "true");
                prop.setProperty("mail.smtp.port", "587");
                prop.setProperty("mail.smtp.auth", "true");

                String correoEnvio = "rodripereira2625@gmail.com";
                String contrasena = "26280259rodrigo";
                String enviar = cor.getCorreo();
                String asunto = "Recuperación";
                String mensaje = "Código de recuperación " + codigo;

                try {
                    mail.setFrom(new InternetAddress(correoEnvio));
                    mail.addRecipient(Message.RecipientType.TO, new InternetAddress(enviar));
                    mail.setSubject(asunto);
                    mail.setText(mensaje);

                    Transport transporte = ses.getTransport("smtp");
                    transporte.connect(correoEnvio, contrasena);
                    transporte.sendMessage(mail, mail.getRecipients(Message.RecipientType.TO));
                    transporte.close();
                    JOptionPane.showMessageDialog(null, "Se envió un e-mail de recuperación a " + cor.getCorreo());
                    panelPass.setVisible(true);
                    codigo4.setEditable(true);

                } catch (AddressException ex) {
                    Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
                    ex.printStackTrace();
                } catch (MessagingException ex) {
                    Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
                    ex.printStackTrace();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "E-mail no registrado");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ocultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ocultarMouseClicked

        ocultar.setVisible(false);
        ocultar.setEnabled(false);

        mostrar.setVisible(true);
        mostrar.setEnabled(true);

        pass1.setEchoChar((char) 8226);
        pass2.setEchoChar((char) 8226);
    }//GEN-LAST:event_ocultarMouseClicked

    private void mostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarMouseClicked

        mostrar.setVisible(false);
        mostrar.setEnabled(false);
        ocultar.setVisible(true);
        ocultar.setEnabled(true);
        pass1.setEchoChar((char) 0);
        pass2.setEchoChar((char) 0);
    }//GEN-LAST:event_mostrarMouseClicked

    private void pass1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pass1MouseClicked

    }//GEN-LAST:event_pass1MouseClicked

    private void pass2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass2FocusGained

        jLabel4.setText("");
        confirmar.setEnabled(true);
    }//GEN-LAST:event_pass2FocusGained

    private void pass1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass1FocusGained
        jLabel2.setText("");
    }//GEN-LAST:event_pass1FocusGained

    private void codigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoFocusGained
        jLabel1.setText("");
    }//GEN-LAST:event_codigoFocusGained

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed

        if (!codigo4.equals("")) {
            cor.setCodigo(Integer.parseInt(codigo4.getText()));
        }
        cor.setCorreo(correo.getText());
        int codigo1 = sql.verifiarCodigo(cor);

        if (!correo.getText().equals("")) {
            if (codigo1 == 1) {
                if (!pass1.getPassword().equals("") && !pass2.getPassword().equals("")) {

                    String pass = new String(pass1.getPassword());
                    String repetir = new String(pass2.getPassword());

                    if (pass.equals(repetir)) {

                        if (pass.length() >= 6) {

                            String contra = CifradoContraseña.sha1(pass);
                            sql.updateContraseña(contra, cor);
                            JOptionPane.showMessageDialog(null, "Contraseña cambiada con éxito");
                            this.dispose();

                            try {
                                Thread.sleep(500);
                                Login lol = new Login();
                                lol.setVisible(true);
                                lol.requestFocus();
                            } catch (InterruptedException ex) {
                                Logger.getLogger(recuperacion.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Contraseña insegura");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "El código ingresado no es correcto");
            }

        } else {
            JOptionPane.showMessageDialog(null, "No ingresó ningún correo");
        }
    }//GEN-LAST:event_confirmarActionPerformed

    private void codigo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigo4ActionPerformed
        jLabel1.setText("");
    }//GEN-LAST:event_codigo4ActionPerformed

    private void codigo4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigo4FocusGained
        jLabel1.setText("");
    }//GEN-LAST:event_codigo4FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recuperacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField codigo1;
    private javax.swing.JTextField codigo2;
    private javax.swing.JTextField codigo3;
    private javax.swing.JTextField codigo4;
    private javax.swing.JButton confirmar;
    private javax.swing.JTextField correo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblmail;
    private javax.swing.JLabel lblmail1;
    private javax.swing.JLabel lblmail2;
    private javax.swing.JLabel lblmail3;
    private javax.swing.JLabel lblmail4;
    private javax.swing.JLabel lblmail5;
    private javax.swing.JLabel mostrar;
    private javax.swing.JLabel ocultar;
    private javax.swing.JPanel panelConfirm;
    private javax.swing.JPanel panelPass;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JPasswordField pass2;
    // End of variables declaration//GEN-END:variables
}
